config/routes.rb
Rails.application.routes.draw do
  resources :users
  root 'static_pages#index'
  resources :cheeses
  resources :monkeys
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/access_log.rb
class AccessLog < ApplicationRecord
  belongs_to :access_loggable, polymorphic: true
  belongs_to :created_by, class_name: 'User', foreign_key: 'created_by_id', optional: true
  belongs_to :updated_by, class_name: 'User', foreign_key: 'updated_by_id', optional: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cheese.rb
class Cheese < ApplicationRecord
  include AccessLogger
end

app/models/monkey.rb
class Monkey < ApplicationRecord
  include AccessLogger
end

app/models/user.rb
class User < ApplicationRecord
  include AccessLogger

  has_many :access_logs_created, class_name: 'AccessLog', foreign_key: 'created_by_id'
  has_many :access_logs_updated, class_name: 'AccessLog', foreign_key: 'updated_by_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cheeses_controller.rb
class CheesesController < ApplicationController
  before_action :set_cheese, only: [:show, :edit, :update, :destroy]

  def create
    temp_cheese_params = cheese_params
    temp_cheese_params[:access_user] = User.first
    @cheese = Cheese.new temp_cheese_params
    respond_to do |format|
      if @cheese.save
        format.html {redirect_to @cheese, notice: 'Cheese was successfully created.'}
        format.json {render :show, status: :created, location: @cheese}
      else
        format.html {render :new}
        format.json {render json: @cheese.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @cheese.destroy
    respond_to do |format|
      format.html {redirect_to cheeses_url, notice: 'Cheese was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def edit
  end

  def index
    @cheeses = Cheese.all
  end

  def new
    @cheese = Cheese.new
  end

  def show
  end

  def update
    temp_cheese_params = cheese_params
    temp_cheese_params[:access_user] = User.last
    @cheese.assign_attributes temp_cheese_params
    respond_to do |format|
      if @cheese.save
        format.html {redirect_to @cheese, notice: 'Cheese was successfully updated.'}
        format.json {render :show, status: :ok, location: @cheese}
      else
        format.html {render :edit}
        format.json {render json: @cheese.errors, status: :unprocessable_entity}
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cheese
    @cheese = Cheese.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def cheese_params
    params.require(:cheese).permit(:name)
  end
end

app/controllers/monkeys_controller.rb
class MonkeysController < ApplicationController
  before_action :set_monkey, only: [:show, :edit, :update, :destroy]

  def create
    temp_monkey_params = monkey_params
    temp_monkey_params[:access_user] = User.first
    @monkey = Monkey.new temp_monkey_params
    respond_to do |format|
      if @monkey.save
        format.html {redirect_to @monkey, notice: 'Monkey was successfully created.'}
        format.json {render :show, status: :created, location: @monkey}
      else
        format.html {render :new}
        format.json {render json: @monkey.errors, status: :unprocessable_entity}
      end
    end
  end

  def edit
  end

  def index
    @monkeys = Monkey.all
  end

  def new
    @monkey = Monkey.new
  end

  def show
  end

  def update
    temp_monkey_params = monkey_params
    temp_monkey_params[:access_user] = User.last
    @monkey.assign_attributes temp_monkey_params
    respond_to do |format|
      if @monkey.save
        format.html {redirect_to @monkey, notice: 'Monkey was successfully updated.'}
        format.json {render :show, status: :ok, location: @monkey}
      else
        format.html {render :edit}
        format.json {render json: @monkey.errors, status: :unprocessable_entity}
      end
    end
  end

  def destroy
    @monkey.destroy
    respond_to do |format|
      format.html {redirect_to monkeys_url, notice: 'Monkey was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_monkey
    @monkey = Monkey.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def monkey_params
    params.require(:monkey).permit(:name)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cheeses_helper.rb
module CheesesHelper
end

app/helpers/monkeys_helper.rb
module MonkeysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cheeses/_form.html.erb
<%= form_with(model: cheese, local: true) do |form| %>
  <% if cheese.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cheese.errors.count, "error") %> prohibited this cheese from being saved:</h2>

      <ul>
      <% cheese.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cheese_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cheeses/edit.html.erb
<h1>Editing Cheese</h1>

<%= render 'form', cheese: @cheese %>

<%= link_to 'Show', @cheese %> |
<%= link_to 'Back', cheeses_path %>

app/views/cheeses/index.html.erb
<div><%= link_to 'Home', root_path %></div>
<p id="notice"><%= notice %></p>

<h1>Cheeses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cheeses.each do |cheese| %>
      <tr>
        <td><%= cheese.name %></td>
        <td><%= link_to 'Show', cheese %></td>
        <td><%= link_to 'Edit', edit_cheese_path(cheese) %></td>
        <td><%= link_to 'Destroy', cheese, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cheese', new_cheese_path %>

app/views/cheeses/new.html.erb
<h1>New Cheese</h1>

<%= render 'form', cheese: @cheese %>

<%= link_to 'Back', cheeses_path %>

app/views/cheeses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cheese.name %>
</p>

<%= link_to 'Edit', edit_cheese_path(@cheese) %> |
<%= link_to 'Back', cheeses_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PolymorphicLocalhost</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monkeys/_form.html.erb
<%= form_with(model: monkey, local: true) do |form| %>
  <% if monkey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(monkey.errors.count, "error") %> prohibited this monkey from being saved:</h2>

      <ul>
      <% monkey.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :monkey_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/monkeys/edit.html.erb
<h1>Editing Monkey</h1>

<%= render 'form', monkey: @monkey %>

<%= link_to 'Show', @monkey %> |
<%= link_to 'Back', monkeys_path %>

app/views/monkeys/index.html.erb
<div><%= link_to 'Home', root_path %></div>
<p id="notice"><%= notice %></p>

<h1>Monkeys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @monkeys.each do |monkey| %>
      <tr>
        <td><%= monkey.name %></td>
        <td><%= link_to 'Show', monkey %></td>
        <td><%= link_to 'Edit', edit_monkey_path(monkey) %></td>
        <td><%= link_to 'Destroy', monkey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Monkey', new_monkey_path %>

app/views/monkeys/new.html.erb
<h1>New Monkey</h1>

<%= render 'form', monkey: @monkey %>

<%= link_to 'Back', monkeys_path %>

app/views/monkeys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @monkey.name %>
</p>

<%= link_to 'Edit', edit_monkey_path(@monkey) %> |
<%= link_to 'Back', monkeys_path %>

app/views/static_pages/index.html.erb
<h2><%= link_to 'Cheeses', cheeses_path %></h2>
<h2><%= link_to 'Monkeys', monkeys_path %></h2>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>